### ISSUE TITLE
put it on stackage?

### ISSUE THREAD

**Issue by debug-ito** [msakai/data-interval#1]
Could you put this package to stackage?

I think this package (and its dependency `extended-reals`) is useful for many applications and libraries and they are well-maintained.

**Comment by msakai** [comment]
Sorry for the late reply and thank you for the suggestion.
I'll try to do so.

**Comment by kaznak** [comment]
I also think this library is useful.

Could you possibly add them to Stackage?

The addition seems to be simple in the following documents: 
https://github.com/commercialhaskell/stackage#add-your-package
https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by Bodigrim** [comment]
Done, https://www.stackage.org/nightly-2019-10-26/package/data-interval-2.0.1

**Comment by msakai** [comment]
Bodigrim, Thanks a lot!
