### ISSUE TITLE
Data.Vector.Unboxed instances

### ISSUE THREAD

**Issue by msakai** [msakai/data-interval#15]
https://github.com/msakai/data-interval/pull/7
> This representation also allows to write an instance of `Data.Vector.Unboxed`, which will require only (2 words + 1 byte) per value. (I cannot include it into PR, because currently `data-interval` does not depend on `vector`).

@Bodigrim, do you want to include the instances in version 2.0.0?

**Comment by Bodigrim** [comment]
Not really, I doubt it is worth a trouble at the moment.

**Comment by msakai** [comment]
I see. Then I think we are almost ready to release version 2.0.0.

**Comment by Bodigrim** [comment]
Yep, I believe we are good to go.

**Comment by msakai** [comment]
I just released 2.0.0 to Hackage.
I close the issue at the moment. If you want the feature again, please re-open the issue.
