### ISSUE TITLE
Allen's interval algebra

### ISSUE THREAD

**Issue by marcosh** [msakai/data-interval#17]
I recently implemented my own version of the possible relations occurring between intervals in https://github.com/marcosh/availer/blob/master/src/Availer/Relation.hs.

As suggested by @Bodigrim on reddit, it could be interesting to add this to `data-interval`. Would you be interested in a PR for this?

**Comment by Bodigrim** [comment]
Yes, as discussed, I think it would be nice to have this vocabulary of relations, and express existing comparison operators in its terms.
