### ISSUE TITLE
Corner cases of `relate`

### ISSUE THREAD

**Issue by Bodigrim** [msakai/data-interval#31]
```haskell
> (NegInf<..<=0) `relate` (0<..<PosInf)
JustBefore -- I'd expect Before
> (NegInf<..<=0) `relate` (0<=..<PosInf)
Overlaps   -- I'd expect JustBefore
```

CC @marcosh what do you think?

**Comment by marcosh** [comment]
I think the returned values are correct.

`JustBefore` means that the intersection of the two intervals is empty and their union is a single interval
`Overlaps` means that the intersection is not empty but no interval is contained in the other

see also http://marcosh.github.io/post/2020/05/04/intervals-and-their-relations.html

**Comment by Bodigrim** [comment]
@marcosh thanks, makes sense!
