### ISSUE TITLE
Self-explaining type for interval boundaries

### ISSUE THREAD

**Issue by Bodigrim** [msakai/data-interval#4]
I noticed that I repeatedly forget the meaning of `Bool` in `(Extended r, Bool)`: does it stand for an open interval or for a closed one? Surely, one can always refer to haddocks, but maybe it is worth to make this parameter self-explaining? Like 

```haskell
data Strictness = Strict | NonStrict
```

or 

```haskell
data Boundary = Open | Closed 
```

**Comment by msakai** [comment]
Thanks for the suggestion.
I agree with you, though I haven't made up my mind yet what name to use.

**Comment by Bodigrim** [comment]
I personally prefer the second one: `data Boundary = Open | Closed`, because we say that "this interval is closed" or "that interval is open", but never "these intervals are strict" or "those intervals are not strict". Constructors are both shorter and have bigger Levenshtein distance in between than in the first alternative.

**Comment by Bodigrim** [comment]
I talked to colleagues around and all of them preferred `Open | Closed`. It was neither large nor random sample, of course :) 

If you make your mind for either name, I would be glad to prepare a PR.

**Comment by msakai** [comment]
Sorry for the late reply.
I also prefer `Open | Closed`.
